spring:
  config:
    import: optional:configserver:http://${CONFIG_HOST:127.0.0.1}:${CONFIG_PORT:8888}/
  cloud:
    config:
      name: user-service
  application:
    name: user-service
  profiles:
    active: local
    include:
      - redis
      - datasource
      - security
      - openfeign
      - eureka
      - actuator
