spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://127.0.0.1:8888/
  profiles:
    active: local
    include:
      - redis
      - datasource
      - security
      - openfeign
      - eureka